---
driver:
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

platforms:
- name: centos-7-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: centos-8-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: debian-8-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: debian-9-0-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: fedora-19-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: fedora-20-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB

- name: ubuntu-16-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: ubuntu-18-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: ubuntu-20-04-x64
  driver_plugin: digitalocean
  driver_config:
    flavor: 512MB
  run_list: ["recipe[apt]"]

- name: amazon-2
  driver_plugin: ec2
  driver_config:
    image_id: ami-02354e95b39ca8dec
    flavor_id: t2.micro
    username: ec2-user
<% if ENV['SSH_AGENT_PID'].nil? %>
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
<% end %>
