---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  <% if ENV.key?('CHEF_VERSION') %>
  product_version: <%= ENV['CHEF_VERSION'].sub(/^.*> (.*)[.][0-9]+$/, '\1') %>
  <% else %>
  product_version: 16
  <% end %>
  deprecations_as_errors: true
  chef_license: accept-no-persist

platforms:
- name: centos-6
- name: centos-7
- name: centos-8
- name: debian-8
- name: debian-9
- name: fedora-latest
# FreeBSD platform requires to run kitchen verify twice by hand
# - name: freebsd-9.2
# - name: freebsd-10.0
- name: opensuse-leap-42
- name: ubuntu-16.04
- name: ubuntu-18.04
- name: ubuntu-20.04

suites:
- name: default
  run_list:
  - recipe[ssh_authorized_keys_test::default]
- name: resource
  run_list:
    - recipe[ssh_authorized_keys_test::resource]
